server:
  port: 8082

spring:
  application:
    name: hazard-service
  # Database
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hazarddb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    # Redis
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

resilience4j:
  circuitbreaker:
    instances:
      weather-api:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
      routing-api:
        sliding-window-size: 10
        failure-rate-threshold: 50

# External API Keys
openweather:
  api:
    key: ${OPENWEATHER_API_KEY}
    url: https://api.openweathermap.org/data/2.5/weather

# Routing API Configuration
# Options: openrouteservice (FREE, no credit card), mapbox, or leave empty for direct path
routing:
  api:
    provider: ${ROUTING_PROVIDER:openrouteservice}
  key: ${ROUTING_API_KEY}
  url: ${ROUTING_API_URL:https://api.openrouteservice.org/v2/directions/foot-walking}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com:
      rahi:
        hazardservice: INFO
    org:
      springframework:
        web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
